- name: Setup a new Ubuntu server
  hosts: webserver
  become: yes # Run tasks as root
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - docker.io
          - docker-compose
          - nodejs
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom Nginx config
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.html;
              server_name _;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
