---
- name: Setup a new Ubuntu server
  hosts: webserver
  become: true
  tasks:
    - name: Update and upgrade APT packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - docker.io
          - docker-compose
          - certbot
          - python3-certbot-nginx
          - ufw
        state: present

    - name: Start and enable Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy custom Nginx config
      copy:
        dest: /etc/nginx/sites-available/default
        content: |
          server {
              listen 80 default_server;
              listen [::]:80 default_server;
              root /var/www/html;
              index index.html;
              server_name _;
              
              location / {
                  try_files $uri $uri/ =404;
              }
          }
      notify: Restart Nginx

    - name: Download NVM installation script
      become: false
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Add NVM to bash profile
      become: false
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR NVM"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

    - name: Install Node.js with NVM
      become: false
      shell: |
        export NVM_DIR="$HOME/.nvm"
        . "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm alias default 'lts/*'
        nvm use default
      args:
        executable: /bin/bash

    - name: Install PM2 globally
      become: false
      shell: |
        . ~/.nvm/nvm.sh
        npm install -g pm2
      args:
        executable: /bin/bash

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
